apiVersion: v1
kind: Service
metadata:
  name: esp32-dht22
  namespace: monitoring
  labels:
    k8s-app: esp32-dht22
spec:
  type: ExternalName
  externalName: 192.168.2.100
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 80
