{
 "title": "ESP WiFi Thermometer",
 "description": "Shows the Temperature and Relative Humidity as measured by an ESP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "The ambient temperature measured by the ESP.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "esptherm_external_temperature_celsius",
     "legendFormat": "Temperature ({{instance}})"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "description": "The ambient relative humidity measured by the ESP.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "esptherm_external_humidity_percent",
     "legendFormat": "Relative Humidity ({{instance}})"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "description": "The number of HTTP requests the ESP handled per path and returned HTTP status code.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(esptherm_http_requests_total[2m])",
     "legendFormat": "Requests to {{instance}}{{path}} with response code {{code}}"
    }
   ]
  }
 ]
}