apiVersion: v1
kind: Service
metadata:
  name: esp-wifi-thermometer
  namespace: monitoring
  labels:
    k8s-app: esp-wifi-thermometer
spec:
  type: ExternalName
  externalName: 192.168.2.101
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: v1
kind: Endpoints
metadata:
  name: esp-wifi-thermometer
  namespace: monitoring
  labels:
    k8s-app: esp-wifi-thermometer
subsets:
- addresses:
  - ip: 192.168.2.101
  ports:
    - name: metrics
      port: 80
      protocol: TCP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: esp-wifi-thermometer-sm
  namespace: monitoring
  labels:
    k8s-app: esp-wifi-thermometer
spec:
  selector:
    matchLabels:
      k8s-app: esp-wifi-thermometer
  namespaceSelector:
    matchNames:
    - monitoring
  jobLabel: esp-wifi-thermometer-exporter
  endpoints:
  - interval: 10s
    port: metrics
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
