# This workflow builds all platformio build targets to test whether any of them were broken by a commit.

name: Platform IO build

on: 
  push:
    paths:
      - src/**
      - lib/**
      - test/**
      - include/**
      - platformio.ini
      - .github/workflows/pio.yml
  pull_request:
    paths:
      - src/**
      - lib/**
      - test/**
      - include/**
      - platformio.ini
      - .github/workflows/pio.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Platform IO
        run: pip install -U platformio

      - name: Run Platform IO builds
        run: pio run
